### ISSUE TITLE
Missing dependency lager

### ISSUE THREAD

**Issue by essen** [biokoda/actordb_thrift#1]
Hi, this project is missing a dependency on lager in the rebar.config, making it harder to use standalone. There might be other missing dependencies.

Also the .app.src file should include those dependencies, including lager.

**Comment by SergejJurecko** [comment]
Removed lager as it was unnecessary anyway. Added thrift to app.src

**Comment by essen** [comment]
Perfect! Will be pushed to the index in a few minutes. Thanks!
